### ISSUE TITLE
Spaces instead of tabs?

### ISSUE THREAD

**Issue by yurket** [opencast/pyCA#13]
Pylint warns, that indentations are made with tabs instead of spaces. It has a point, because the length of tabs may differ from editor to editor, system to system.

**Comment by lkiesow** [comment]
…which is totally irrelevant unless you start mixing tabs and spaces which is indeed a very bad idea ;-)
The only valid reason I can come up with is PEP8 which recommends the use of spaces for new projects.
The downside of this conversion would be that the whole code would have to be modified.
Any other argument for doing this conversion?

**Comment by yurket** [comment]
Nope =) It was just a proposal. It totally on you to decide which indentation style to use.

**Comment by lkiesow** [comment]
Thought about this for a bit and decided to go with spaces after all ;-)
Commit 8928170 converts tabs to spaces and fixes most of the other pylint warnings.

**Comment by yurket** [comment]
Great! My editor will not glow like a Christmas tree with pylint warns =)

**Comment by lkiesow** [comment]
Hahaha...
It will still show some show y couple of bare excepts though.
