### ISSUE TITLE
Issue when starting PyCA

### ISSUE THREAD

**Issue by juanpanie** [opencast/pyCA#132]
Hello, I've been trying to run PyCA but I having this error when running the start scrip: 

root@ip-10-237-5-67:~/pyCA# ./start.sh
[pyca.config:129:logger_init()] [INFO] Log level set to debug
[pyca.config:89:update_configuration()] [INFO] Configuration loaded from ./etc/pyca.conf
[pyca.utils:78:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080//capture-admin
[pyca.utils:78:get_service()] [INFO] Endpoint for org.opencastproject.ingest: http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080//ingest
[pyca.utils:78:get_service()] [INFO] Endpoint for org.opencastproject.scheduler: http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080//recordings
[pyca.utils:78:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080//capture-admin
[pyca.utils:78:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080//capture-admin
[pyca.utils:147:register_ca()] [WARNING] Could not set agent statei to offline: (22, 'The requested URL returned error: 405 HTTP method POST is not supported by this URL')
[pyca.schedule:69:get_schedule()] [ERROR] Could not get schedule: (22, 'The requested URL returned error: 404 Not Found')

Then, I cannot see the location in my OC server http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080. 

Im using PyCA 2.1 and OC 2.3.0 

Thanks in advance.

**Comment by lkiesow** [comment]
Just a guess, but did you set

    url =  http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080/
 if you, can you try setting it to

    url =  http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080

…without the final `/`

**Comment by juanpanie** [comment]
Hi Lars, yes, I've tried with the / and without the /

My conf looks like this: 

```
# URL of the admin server.
# Type: string
# Default: https://octestallinone.virtuos.uos.de
url              = 'http://ec2-XX-XXX-XX-XX.us-west-1.compute.amazonaws.com:8080'`
```

I have no idea why the log is showing // when pointing to the OC services.

**Comment by lkiesow** [comment]
They should not appear out of nowhere ;-)

My second guess is that there is a `/` at the end of `org.opencastproject.server.url` in your Opencast configuration. The service endpoint locations are requested from Opencast, hence it is likely that they come from there. Can you check if there is not `/` either?

**Comment by juanpanie** [comment]
OMG!! Too close to see it! ;-) 

I've changed the `org.opencastproject.server.url` and removed the `/` and is working. Now im able to check next steps on how to use pica for recording. 

Thanks so much for your input Lars!
