### ISSUE TITLE
never ending uploads

### ISSUE THREAD

**Issue by miguelgusils** [opencast/pyCA#136]
Recordings greater than 1 hour never finish uploading to OC. 
sends endless amount of traffic.
-The recordings play fine if manually downloaded.  
I was able to schedule 10x 5 minute recordings which all finished successfully

pyCA 2.1 OC 1.6+

**Comment by lkiesow** [comment]
That sounds weird since there needs to be a data source and someone who is taking all the data. I've also never seen something like this. Even with longer recordings/larger ingests.

The only thing I can come up with is that curl is trying to recover from a nonce-timeout but I find that quite unlikely.

I'd be interested to see what the files look like after the expected cutoff point

- is it ingesting things N times concatenated?
- or is it totally garbled?
- or are there N ingests?

Can you

- Check the Opencast logs
- Check the pyCA logs (are they reporting an ingest one or multiple times)
- Maybe check what files are written to the workspace?

**Comment by JanKoppe** [comment]
I've never encountered that either. We do need more logs for that (pyCA and Opencast side) for that, maybe even wireshark the connection to see what's going on. Are you proxying your Opencast cluster? Maybe a upload size limit?

**Comment by miguelgusils** [comment]
I agree it's odd. If multiple 5minute capture succeeds then the config appears to be correct.
pyca:
-receives the schedule 
-starts / stops recording 
-starts uploading ..never stops. it does seem to be resending 

my 1 hour recordings are ~3gb. Using iftop and letting is run for 2hours i observed it transmitted ~300gb but never completed no file on the OC server. 
nothing odd, no error in the OC logs 

pyca - logs:
Jun  7 11:05:04 dev-altcap01 [pyca.utils:166:recording_state()] [INFO] 1421 set to capture_finished
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.utils:166:recording_state()] [INFO] 1421 set to capture_finished
Jun  7 11:05:04 dev-altcap01 [pyca.utils:166:recording_state()] [INFO] 1421 set to uploading
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.utils:166:recording_state()] [INFO] 1421 set to uploading
Jun  7 11:05:04 dev-altcap01 [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to uploading
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to uploading
Jun  7 11:05:04 dev-altcap01 [pyca.ingest:54:ingest()] [INFO] Selecting ingest service to use: http://ip-10-1-4-53.ec2.internal/ingest
Jun  7 11:05:04 dev-altcap01 [pyca.ingest:57:ingest()] [INFO] Creating new mediapackage
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.ingest:54:ingest()] [INFO] Selecting ingest service to use: http://ip-10-1-4-53.ec2.internal/ingest
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.ingest:57:ingest()] [INFO] Creating new mediapackage
Jun  7 11:05:04 dev-altcap01 [pyca.ingest:71:ingest()] [INFO] Adding episode DC catalog
Jun  7 11:05:04 dev-altcap01 python[6574]: [pyca.ingest:71:ingest()] [INFO] Adding episode DC catalog
Jun  7 11:05:05 dev-altcap01 [pyca.ingest:71:ingest()] [INFO] Adding series DC catalog
Jun  7 11:05:05 dev-altcap01 python[6574]: [pyca.ingest:71:ingest()] [INFO] Adding series DC catalog
Jun  7 11:05:05 dev-altcap01 [pyca.ingest:79:ingest()] [INFO] Adding track (presenter/source -> /home/data/recording-1496846100-1421/presenter.mp4)
Jun  7 11:05:05 dev-altcap01 python[6574]: [pyca.ingest:79:ingest()] [INFO] Adding track (presenter/source -> /home/data/recording-1496846100-1421/presenter.mp4)
Jun  7 11:05:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:05:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:06:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:06:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:07:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:07:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:08:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:08:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:09:01 dev-altcap01 CRON[20996]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean)
Jun  7 11:09:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:09:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:10:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:10:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:11:14 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun  7 11:11:14 dev-altcap01 python[6574]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording


-----
..so it has sent 84gb, and will keep going.

TX:             cum:   84.2GB   peak:    621Mb                                                                                                                 rates:    387Mb   339Mb   416Mb
RX:                     466MB           3.03Mb                                                                                                                          2.79Mb  2.31Mb  2.55Mb
TOTAL:                 84.7GB            623Mb                                                                                                                           390Mb   341Mb   419Mb


---
there is no proxy our production-CA's we are comparing to uploads 2hr video. 

thoughts?

**Comment by miguelgusils** [comment]
additional info: 
if i download the files they play perfectly. if uploaded to OC they process normally.
if the file is > 30 minutes it uploads forever. if < 30 it works perfectly. is nobody else running into this?

**Comment by JanKoppe** [comment]
Can you report the curl/libcurl versions for us? And have you tried a similar scenario with a different CA software like Galicaster CE? Just trying to narrow the error down. But no, I've not seen this error before and it's really strange. My best guess is libcurl acting up, but that would be a very slim chance.

**Comment by miguelgusils** [comment]
hi 
curl (7.47.0-1ubuntu2.2) 
i’ve installed a second CA to see if i can reproduce the issue
i agree it is odd. the files being generated via ffmpeg play fine if downloaded manually.
i’ve narrowed it down to being able to schedule captures 15minutes successfully 
but 30 minutes or greater the CA uploads continuously. 
other than file size i see no difference

**Comment by miguelgusils** [comment]
I reinstalled from bare-metal and the issue has gone away. Maybe it was a libcurl issue/conflict

**Comment by miguelgusils** [comment]
No recordings upload.
after reinstalling i was able to upload 1x 2hour recording, after that all uploads of any length 
do not finish uploading. there is are no errors in the logs. is there a way to kickstart ingest?
the recording finish and look/play fine.

python[2056]: video:2666138kB audio:4416kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Jun 17 09:13:03 dev-altcap01 python[2056]: [aac @ 0x55d2c8189600] Qavg: 1431.943
Jun 17 09:13:03 dev-altcap01 [pyca.utils:166:recording_state()] [INFO] 1809 set to capture_finished
Jun 17 09:13:03 dev-altcap01 python[2056]: [pyca.utils:166:recording_state()] [INFO] 1809 set to capture_finished
Jun 17 09:13:03 dev-altcap01 [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to idle
Jun 17 09:13:03 dev-altcap01 python[2056]: [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to idle
Jun 17 09:13:04 dev-altcap01 [pyca.utils:166:recording_state()] [INFO] 1809 set to uploading
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.utils:166:recording_state()] [INFO] 1809 set to uploading
Jun 17 09:13:04 dev-altcap01 [pyca.ingest:54:ingest()] [INFO] Selecting ingest service to use: http://ip-10-1-7-32.ec2.internal/ingest
Jun 17 09:13:04 dev-altcap01 [pyca.ingest:57:ingest()] [INFO] Creating new mediapackage
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.ingest:54:ingest()] [INFO] Selecting ingest service to use: http://ip-10-1-7-32.ec2.internal/ingest
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.ingest:57:ingest()] [INFO] Creating new mediapackage
Jun 17 09:13:04 dev-altcap01 [pyca.ingest:71:ingest()] [INFO] Adding episode DC catalog
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.ingest:71:ingest()] [INFO] Adding episode DC catalog
Jun 17 09:13:04 dev-altcap01 [pyca.ingest:71:ingest()] [INFO] Adding series DC catalog
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.ingest:71:ingest()] [INFO] Adding series DC catalog
Jun 17 09:13:04 dev-altcap01 [pyca.ingest:79:ingest()] [INFO] Adding track (presenter/source -> /home/data/recording-1497704880-1809/presenter.mp4)
Jun 17 09:13:04 dev-altcap01 python[2056]: [pyca.ingest:79:ingest()] [INFO] Adding track (presenter/source -> /home/data/recording-1497704880-1809/presenter.mp4)
Jun 17 09:13:16 dev-altcap01 [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to uploading
Jun 17 09:13:16 dev-altcap01 python[2056]: [pyca.utils:145:register_ca()] [INFO] dev-altcap01 set to uploading
Jun 17 09:13:16 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun 17 09:13:16 dev-altcap01 python[2056]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun 17 09:14:16 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun 17 09:14:16 dev-altcap01 python[2056]: [pyca.schedule:107:control_loop()] [INFO] No scheduled recording
Jun 17 09:15:16 dev-altcap01 [pyca.schedule:107:control_loop()] [INFO] No scheduled recording

**Comment by miguelgusils** [comment]
turned out not to be a pyca issue, rather an nginx issue on OC. large files were being cached to directory which was too small.
