### ISSUE TITLE
Log successful end of capture

### ISSUE THREAD

**Issue by smarquard** [opencast/pyCA#139]
Currently start of capture is logged and recording failure is logged, but a successful end of capture is not logged.

For consistency & better confidence, log a "Recording finished" message when it succeeds.

**Comment by lkiesow** [comment]
Do you mean logging:

- End of capture?
- End of upload?
- Both?

**Comment by smarquard** [comment]
I think both if relevant would be helpful. For a CA in backup mode, there would only be end of capture.
