### ISSUE TITLE
Check and/or sanitize CA name setting

### ISSUE THREAD

**Issue by mpmuc84** [opencast/pyCA#146]
Since the name of the CA is part of the URL used for registration and configuration, the content of this variable should be checked and/or sanitized to conform with [RFC 3986](https://tools.ietf.org/html/rfc3986) to allow for safe and working URL building.

E.g. if a user sets their CA name to 'Test Capture Agent (1/2)', registration will fail due to the spaces as well as the slash between the two digits. To the receiving Opencast endpoint, the CA name according to the request URL differs from the CA name according to the message body, which leads to a generic 400 error code being returned, while pyCA continues to run.

A solution could vary from simply including another step in the validation function (with the CA stopping and giving an error message for the user in case of non-conforming settings, as well as information in the documentation), up to active transformation of the user setting at runtime (e.g. 'Test Capture Agent (1/2)' becomes something like 'Test%20Capture%20Agent%20%281%2F2%29' to preserve the human readable version, or something like 'test_capture_agent__1_2_' through simple substitution of everything not alphanumeric in the string).

**Comment by lkiesow** [comment]
Good point. Never noticed that problem.

I've just verified that URL encoding the agent's name seems to work fine. Hence using `Test%20Capture%20Agent%20%281%2F2%29` will let the agent appear in the admin interface like the user would expect it to. Also, URL encoding should be easy to implement.

**Comment by lkiesow** [comment]
@mpmuc84, can you check if pull request #147 fixes the issue for you?

**Comment by mpmuc84** [comment]
Sorry for the delay, I was not able to test your modifications before today. Thanks for the quick response, by the way! :)

Going through the special characters defined in RFC 3986 (gen-delims and sub-delims for URLs), most work fine with this change. Two characters continue to be problematic: '/' and ';'

When I set `name = 'Testing / Capture Agent'`, I get the following output:
```
[pyca.config:133:logger_init()] [INFO] Log level set to info
[pyca.config:93:update_configuration()] [INFO] Configuration loaded from ./etc/pyca.conf
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.ingest: https://<ADMIN_SERVER>:443/ingest
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.scheduler: https://<ADMIN_SERVER>:443/recordings
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.utils:149:register_ca()] [WARNING] Could not set agent statei to idle: (22, 'The requested URL returned error: 404 Not Found')
[pyca.schedule:116:control_loop()] [INFO] No scheduled recording
^C
[pyca.schedule:123:control_loop()] [INFO] Shutting down schedule service
[pyca.agentstate:31:control_loop()] [INFO] Shutting down agentstate service
[pyca.ingest:132:control_loop()] [INFO] Shutting down ingest service
[pyca.capture:161:control_loop()] [INFO] Shutting down capture service
```

When I set `name = 'Testing ; Capture Agent'`, I get the following output:
```
[pyca.config:133:logger_init()] [INFO] Log level set to info
[pyca.config:93:update_configuration()] [INFO] Configuration loaded from ./etc/pyca.conf
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.scheduler: https://<ADMIN_SERVER>:443/recordings
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.ingest: https://<ADMIN_SERVER>:443/ingest
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://<ADMIN_SERVER>:443/capture-admin
[pyca.schedule:116:control_loop()] [INFO] No scheduled recording
[pyca.utils:147:register_ca()] [INFO] Testing  set to idle
^C
[pyca.schedule:123:control_loop()] [INFO] Shutting down schedule service
[pyca.agentstate:31:control_loop()] [INFO] Shutting down agentstate service
[pyca.capture:161:control_loop()] [INFO] Shutting down capture service
[pyca.ingest:132:control_loop()] [INFO] Shutting down ingest service
```

In the first case, registration fails, and no recordings can be assigned. In the second case, registration succeeds, however, under a shortened version of the name ('Testing ' instead of 'Testing ; Capture Agent').

Most cases should be covered by this fix. However, I would suggest prohibiting users from including a backslash or semicolon in the name, or at least to include this bit of information in the documentation comment within the settings file.

(BTW: The REST docs testing form appears to have the same problem, returning a 405 when including a backslash, and a 200 with cut-off name when including a semicolon.)

**Comment by lkiesow** [comment]
I cannot reproduce your problem when using this patch:

```
% python3 -m pyca
[pyca.config:133:logger_init()] [INFO] Log level set to info
[pyca.config:93:update_configuration()] [INFO] Configuration loaded from ./etc/pyca.conf
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.scheduler: https://develop.opencast.org/recordings
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://develop.opencast.org/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.ingest: https://develop.opencast.org/ingest
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://develop.opencast.org/capture-admin
[pyca.utils:80:get_service()] [INFO] Endpoint for org.opencastproject.capture.admin: https://develop.opencast.org/capture-admin
[pyca.utils:148:register_ca()] [INFO] Testing / Capture Agent set to idle
[pyca.schedule:116:control_loop()] [INFO] No scheduled recording
^C[pyca.agentstate:31:control_loop()] [INFO] Shutting down agentstate service
[pyca.schedule:123:control_loop()] [INFO] Shutting down schedule service
[pyca.capture:161:control_loop()] [INFO] Shutting down capture service
[pyca.ingest:132:control_loop()] [INFO] Shutting down ingest service
```
…same for python2.

I've also tried including `;` and `\;` with no problem:

```
[pyca.utils:148:register_ca()] [INFO] Testing ; Capture Agent set to idle
…
[pyca.utils:148:register_ca()] [INFO] Testing \; Capture Agent set to idle
```

They also show up in the UI properly:

![screenshot from 2018-04-18 11-34-11](https://user-images.githubusercontent.com/1008395/38924311-ec9bcb6e-42fc-11e8-8858-56667ae71148.png)

- Which version of Python are you testing with?
- Which version of Opencast are you using?
- Can you try against [develop.opencast.org](https://develop.opencast.org)? Parts of what you report sounds like an Opencast bug.

**Comment by mpmuc84** [comment]
OK, I have tested against develop.opencast.org, no problems there with any character, as per your tests. At least for the current development snapshot there (V6.0?), this should work.

Opencast on my end is at V4.3.0 (build 28bd9e7), installed on Debian 9 from the official repo.

I run Python 3.6.5 locally on my MacBook and 3.4.6 on a remote test system, did not try Python 2, to be honest.

It looks indeed more like a bug on Opencast's end (though I am not sure yet how to meaningfully report this for someone to potentially fix it).

**Comment by lkiesow** [comment]
Will test against https://stable.opencast.org and https://legacy.opencast.org later today

**Comment by lkiesow** [comment]
Weird. Tested this against stable (5.x) and legacy (4.x) with not problems:

```
[pyca.utils:36:http_request()] [DEBUG] Requesting URL: https://legacy.opencast.org/capture-admin/agents/Testing%20%5C%3B%2F%20Capture%20Agent
[pyca.utils:148:register_ca()] [INFO] Testing \;/ Capture Agent set to idle
```

Can you maybe test legacy as well? That should be closest to your set-up. Also, what's your Opencast set-up? Do you have it running behind a proxy server?

**Comment by mpmuc84** [comment]
Legacy test server works fine for me with your patch, just like on your side.

My setup is indeed running behind an Apache proxy server for HTTPS. I run a four node setup (1 admin, 2 workers, 1 engage), only admin and engage are behind their respective proxy.

I will try this locally on a fresh installation to see if this could be related to my particular setup. Probably not before tomorrow, though.

**Comment by lkiesow** [comment]
develop, stable and legacy are using Nginx as reverse proxy. To check if httpd is the problem: Can you run pyCA on your Opencast admin node setting the server to `http://localhost:8080` (circumventing the proxy)?

**Comment by mpmuc84** [comment]
So, after some testing with my setup and a seperate fresh test environment, I can safely say that this last issue was related only to my particular Apache configuration.

I had to set `AllowEncodedSlashes NoDecode` in the vhost configuration and add the `nocanon` keyword to the `ProxyPass` directive, otherwise the proxy would decode the slashes and thus interpret them as path information. After setting this, I could successfully register CAs even with slashes and semicolons in their name. 

As far as I can see, I believe you can now safely merge #147 and close this issue. I do not see any (potential) problems with your code modifications, and they achieve what they aim to do.

**Comment by lkiesow** [comment]
Interesting. Thanks for doing all the testing, though!
