### ISSUE TITLE
Add Python 3.7 to CI

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#151]
https://github.com/travis-ci/travis-ci/issues/9815 

Travis does not yet support Python 3.7 in CI jobs. The tests run fine on my Python 3.7.0 installation on Arch Linux, so we should be fine for now.

**Comment by lkiesow** [comment]
Technically, it does if we were to include the [3.7-dev](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions) version but so far I hesitated to add non-stable versions. I don't really mind though if you want to.

**Comment by lkiesow** [comment]
Python 3.7 and 3.8 is already tested against
