### ISSUE TITLE
Feature: deploy with balenaCloud

### ISSUE THREAD

**Issue by sebastjanm** [opencast/pyCA#165]
option to deploy to deploy pyCA with balenaCloud
example: https://github.com/balena-io-projects/simple-server-node

**Comment by JanKoppe** [comment]
Hello @sebastjanm,

could you maybe explain a bit more what you actually need for this to work? I don't see the intersection of "balenaCloud" and pyCA - looks like balenaCloud is just a fancy wrapper/orchestrator for Docker at first glance.

Seems like you just want some Dockerfiles available?

**Comment by sebastjanm** [comment]
> Seems like you just want some Dockerfiles available?

yes, kind of .... as you know usually the main obstacle is not to deploy on one device itself, but rather managing an entire fleet of connected linux/Raspberry Pi devices. Services/tools like BalenaCloud can help with this issue. At least from my experience managing/deploying and updating devices is always challenging and time consuming. 

btw .. open source version: https://www.balena.io/open/
