### ISSUE TITLE
Ingest-Node is used even if it is offline

### ISSUE THREAD

**Issue by CGreweling** [opencast/pyCA#168]
pyca tries to ingest to an offline Ingest Node and fails.

**Comment by lkiesow** [comment]
@CGreweling, can you give me the result of:

    % curl -s --digest -u opencast_system_account:CHANGE_ME -H "X-Requested-Auth: Digest" \
        'https://<admin-node>/services/available.json?serviceType=org.opencastproject.ingest' | jq

Feel free to mask the domain but please do it in a way that it's clear what kind of node it is.
