### ISSUE TITLE
SQLite Threading Problem

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#174]
I ran the the PyCA UI with `./start.sh ui` on Arch Linux and visit the website. After some reloads I got the following tracebacks multiple times:

```python
[sqlalchemy.pool.impl.NullPool:272:_close_connection()] [ERROR] Exception closing connection <sqlite3.Connection object at 0x7feb1abca6c0>
Traceback (most recent call last):
  File "/home/sven/devel/elanev/pyCA/venv/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 83, in __init__
    self._empty_listeners = self._empty_listener_reg[instance_cls]
  File "/usr/lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7feb1aaee310; to 'type' at 0x7feb14050460 (Session)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sven/devel/elanev/pyCA/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/sven/devel/elanev/pyCA/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/sven/devel/elanev/pyCA/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 540, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140647752754944 and this is thread id 140647741564672.
```

There are no custom configs or an existing database before. My Environment looks like this:

```bash
$ pip freeze
click==7.1.2
configobj==5.0.6
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
pycurl==7.43.0.5
python-dateutil==2.8.1
sdnotify==0.3.2
six==1.15.0
SQLAlchemy==1.3.17
Werkzeug==1.0.1
$ pacman -Q sqlite
sqlite 3.31.1-1
```

**Comment by shaardie** [comment]
It seems like the underlying `pysqlite` implementation is not thread-safe
https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#threading-pooling-behavior. So there is probably no easy solution to use SQLite safe in multiple threads.

To the specific error:

It seems a problem that occurs on more up to date versions of SQLite (I encountered in on Arch Linux with SQLite 3.32.1).
As far as I understand, it happens during the Teardown of the database connection in another thread.
SQLAlchemy is using `NullPool` for SQLite per default and resets the closes the database connection completely on every query.

A solution I saw multiple times is to use `connect_args={'check_same_thread': False}` during the engine creation, but, as far i can see, this is only silence the error message.

**Comment by lkiesow** [comment]
The reason why this only happens in modern systems and did not appear in the past is probably Flask's newish threading concept. The error does not seem to appear with gunicorn when workers are being used. The error also did not appear on older systems with older Flask versions.

However, Flask ≥ 1.0 did enable threading by default so the development server would perform better. Deactivating this makes the execution single-threaded again and the error disappears.

This shouldn't really be a huge problem given that this is for development and we don't do many large requests.
