### ISSUE TITLE
Unable to locate package libcurl-gnutls-dev

### ISSUE THREAD

**Issue by blackyboy** [opencast/pyCA#2]
Hi @lkiesow 

I have tried to install the pyCA, in Raspberry pi but when ever i try the below command the package unable to locate. Could you please update your documentation with which repo you get the extra packages for pyCA build.

```
sudo apt-get install python-virtualenv python-dev libcurl-gnutls-dev libcurl-gnutls-dev virtualenv venv
Reading package lists... Done
Building dependency tree        
Reading state information... Done
E: Unable to locate package libcurl-gnutls-dev
```

I have tried adding the below source list too 

```
deb http://http.debian.net/debian wheezy main contrib non-free
# deb-src http://ftp.de.debian.org/debian wheezy main contrib non-free
```

But still i can't get the package could you please provide me which repository you used to get the libcurl-gnutls-dev virtualenv venv . except these two packages everything installed without any issue.

Appreciated , Thanks

**Comment by lkiesow** [comment]
Hi,
I don't have a test set-up right here at the moment, but can you try replacing `libcurl-gnutls-dev` with either one of these:
- libcurl4-gnutls-dev
- libcurl4-openssl-dev

So basically, try:

```
sudo apt-get install python-virtualenv python-dev libcurl4-gnutls-dev
```

…and let me know if that works.

**Comment by blackyboy** [comment]
@lkiesow yes this worked for me thanks..

```
sudo apt-get install python-virtualenv python-dev libcurl4-gnutls-dev
```

Everything working fine thank you

**Comment by lkiesow** [comment]
Fixed the documentation in the main readme
