### ISSUE TITLE
Use urllib.parse.urljoin

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#208]
Instead of joining the urls ourself, we could use something like [urllib.parse.urljoin](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin).

It would be more resilient, e.g. with trailing slashes:

```python
urllib.parse.urljoin('http://test.de/', '/banana')
'http://test.de/banana'
```

**Comment by shaardie** [comment]
Okay, this is nonsense. This parser seems to be eben more fragilie with slashes

```python
>>> urllib.parse.urljoin('http://test.de/apple', '/banana')
'http://test.de/banana'
>>> urllib.parse.urljoin('http://test.de/apple', 'banana')
'http://test.de/banana'
>>> urllib.parse.urljoin('http://test.de/apple/', 'banana')
'http://test.de/apple/banana'
>>> urllib.parse.urljoin('http://test.de/apple/', '/banana')
'http://test.de/banana'

```

**Comment by lkiesow** [comment]
> This parser seems to be eben more fragilie with slashes

I vaguely remember that being the standard way of merging URLs. The second argument, in this case, is an absolute path and will thus overwrite the existing path in case there is a leading `/`.  If there is no leading `/`, it's a local path and will be appended.

So, we should probably be able to use it just fine if we wanted to
