### ISSUE TITLE
Allow continuous preview

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#253]
It would be nice to have an option for presenting a continuous preview (even while no recording is active). One easy way to archive this would be an option telling pyCA to stay clear of handling the preview at all, and then having an external process provide the preview files configured in pyCA. This does need some documentation though since this is quite different from the current concept of handling the previews.

**Comment by kristofkeppens** [comment]
I have a script providing the preview image to the correct preview dir, and the UI picks this up and shows this correctly. As far as I see pyca isn't really complaining about this approach. If you're interested I can create the necessary documentation (PR) to set this up ...

**Comment by lkiesow** [comment]
If you want to, please add it to the documentation at https://github.com/opencast/pyCA/blob/main/docs/live-preview.rst

**Comment by lkiesow** [comment]
Fixed by pull request #355

**Comment by mtneug** [comment]
If I remember correctly, pyCA will delete preview images after a recording. It might be a good idea to be able to deactivate that, but the preview will be recreated shortly after that anyway so it's not a big deal.
