### ISSUE TITLE
Don't store and upload metadata catalogs

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#269]
Pull request #268 disables the upload of metadata catalogs by default since Opencast already has these data and doing so is discouraged. While this already improves things, we really don't need that option or the upload. This also means that we don't need to store most attachments.

### To-do

- Remove option `upload_catalogs`
- Remove upload functionality
- Don't store all attachments in the database
- Evaluate if it makes sense to store the properties directly in the database

**Comment by lkiesow** [comment]
Turns out you need this if you use this as a backup and want to re-upload events.
Closing this for now…

**Comment by mtneug** [comment]
We noticed that deleting an event in Opencast after recording starts but before the ingest will also result in recordings with no metadata.
