### ISSUE TITLE
Capturing two usb streams using pyCA

### ISSUE THREAD

**Issue by prabathdj** [opencast/pyCA#276]
Hi,

I have tested capturing a single USB stream at 1080p using gstreamer using pyCA capture agent for studio upload. My requirement is to capture 2 USB streams at 1080p for studio upload which has to be in 2 separate file. What is the method to achieve this?

Thank You

**Comment by pascalzurek** [comment]
Hi prabathdj,
if you would provide your original gstreamer command line, it would be easier to help you.
Guessing that you are using V4L as a source, you just need two of them, piping them to each their filesink. 
May I point you to the gstreamer documentation, which is very complete:
https://gstreamer.freedesktop.org/documentation/plugins_doc.html?gi-language=c

**Comment by prabathdj** [comment]
Hi pascalzurek,

Thank you for the reply. Below is the command that is used in the pyca.conf.

command = 'gst-launch-1.0 -e v4l2src device=/dev/video1 ! video/x-raw, width=1920, height=1080, framerate=30/1 ! queue ! nvvidconv ! nvv4l2vp8enc bitrate=4000000 ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! audio/x-raw,width=16,depth=16,rate=44100,channel=1 ! queue ! audioconvert ! vorbisenc ! webmmux name=mux ! filesink location={{dir}}/{{name}}.webm'

From what you have suggested. Is it possible to use the 'tee' element to link the 2 sources in to a single command and save 2 separate files?
What are the places to change in the pyca.conf to achieve this scenario?

Thank You

**Comment by pascalzurek** [comment]
Hello prabathdj,

quoting from the gstreamer docs, the tee element splits data to multiple pads. You can link one source to two different files with that. This is not what you want.

You are already at the right place in the pyca.conf as this defines the command which is executed to record, as you have already found out yourself.
What you need are two v4l2src elements, pointing to two different devices, and eventually sinking into different filesink elements.
Many examples for gstreamer are noted here:
https://gstreamer.freedesktop.org/documentation/tutorials/basic/gstreamer-tools.html?gi-language=c
Furthermore, you do not necessarily need to use gstreamer if that seems a bit complicated. You could also use ffmpeg or vlc or a bash-script which does multiple things. PyCA just executes a command, no matter what it is.

**Comment by prabathdj** [comment]
Hello pascalzurek,

I found a gstreamer command to record the 2 sources and save into 2 separate files.

command = 'gst-launch-1.0 -e v4l2src device=/dev/video1 ! video/x-raw, width=1920, height=1080, framerate=30/1 ! queue ! nvvidconv ! nvv4l2vp8enc ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! audio/x-raw,width=16,depth=16,rate=44100,channel=1 ! queue ! audioconvert ! vorbisenc ! webmmux name=mux ! filesink location={{dir}}/{{name}}.webm v4l2src device=/dev/video0 ! video/x-raw, width=640, height=480, framerate=30/1 ! queue ! nvvidconv ! nvv4l2vp8enc ! webmmux ! filesink location={{dir}}/{{name}}.webm'

Only one file is saved and uploaded. Is the problem with the naming of files? or Are there any parameters that should be changed in the pyca.conf to have 2 separate files? 

Should the "Flavors" or "Output files" in the pyca.conf be changed. I used the default configuration.

Flavors of output files produced by the capture command. One flavors should
be specified for every output file.
Type: list of strings (write as '...', '...')
Default: 'presenter/source'
flavors          = 'presenter/source'

Output files produces by the capture command.
Type: list of strings (write as '...', '...')
Default: '{{dir}}/{{name}}.webm'
files            = '{{dir}}/{{name}}.webm'

Thank You

**Comment by pascalzurek** [comment]
In Opencast, every file uploaded has a flavor. See the Opencast documentation for this.
So what you need would be one flavor per file (i. e. 'presenter/source', 'presentation/source') and of course two file names ('{{dir}}/{{name1}}.webm', '{{dir}}/{{name2}}.webm').

**Comment by prabathdj** [comment]
Hello pascalzurek,

Thank you for the support.  I will try this method

**Comment by prabathdj** [comment]
Hi pascalzurek,

I was able to capture and upload 2 separate usb streams using pyCA. Thank you very much for the support.
