### ISSUE TITLE
Creating a pyCA initiated event

### ISSUE THREAD

**Issue by prabathdj** [opencast/pyCA#278]
Hi,

I used pyCA to record a video stream when an event is added from the server and it was successful. 

I need to know whether there is a method to upload locally recorded video files without having a prescheduled event on the server.

Thank You

**Comment by lkiesow** [comment]
If you have local video files, it's really easy to use the Opencast API directly. There is no need for pyCA. For example, this will upload a single media file to the public test server:

```sh
curl -i -u admin:opencast https://develop.opencast.org/ingest/addMediaPackage \
  -F 'flavor=presentation/source' \
  -F 'BODY=@sintel_trailer-1080p.mp4' \
  -F title="Some title" \
  -F creator="J. Doe" 
```

You can get more information in the REST docs at:
- https://develop.opencast.org/docs.html?path=/ingest#addMediaPackage-6

There are also a bunch of example script partly doing more complex stuff here:
- https://github.com/opencast/helper-scripts/tree/master/ingest

**Comment by prabathdj** [comment]
Hi lkiesow,

Thank you very much for the help. This method worked only for .mp4 files

Can't we use other file types such as .ts and .webm?

**Comment by lkiesow** [comment]
Sure, you can. Opencast shouldn't mind as long as FFmpeg can deal with it.
A short warning about transport streams though: Quite a few Operations of Opencast need to know the length of the video file. There is no easy way to get that from transport streams. Thus, some operations may fail. A simple (and lossless) solution for that would be to add an operation to your Opencast workflow which just stream-copies the video into a regular container such as mkv.

**Comment by prabathdj** [comment]
Thank you. I will try the solution.
