### ISSUE TITLE
Send status updates at fixed interval

### ISSUE THREAD

**Issue by smarquard** [opencast/pyCA#28]
pyca doesn't send regular status updates to the Opencast server, which means the last-updated time on the CA can get very old.

This can have unwanted side-effects, like monitoring scripts that check CA status could think that a pyCA is offline when in fact it's online.

pyCA should send regular status updates to the Opencast server, consistent with other CAs (e.g. reference CA, galicaster).

**Comment by lkiesow** [comment]
Hi Stephen,
does it really make sense to update the status when there is not status update?
For monitoring, would it not make more sense to monitor pyCA itself?
–Lars

**Comment by smarquard** [comment]
It does make sense, because it informs the Opencast server that the CA is still alive and able to record. The CA could have sent an "idle" status update, and then go offline because of:
1. A network failure
2. A hardware/OS/VM failure
3. A crash of the application itself
4. The application gets hung (e.g. a recording process does not terminate).

In all these cases, it should be possible to determine that the CA is not ready to record for an upcoming recording, e.g. as we do with this alert script which is used for production operations:

http://source.cet.uct.ac.za/svn/matterhorn/scripts/capture-agents-alert.pl

Also this behaviour (sending status updates at a regular interval even status has not changed) is consistent with other CAs (reference CA, and Galicaster).

**Comment by gregorydlogan** [comment]
Lars, the checking behaviour has always been a part of the CA even back to the original spec.  I don't disagree with your position, but not doing that make pyCA not behave to spec...

**Comment by JanKoppe** [comment]
covered with #65
