### ISSUE TITLE
Record after connection to Servers has been lost

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#29]
We've observed that pyCA will not start a recording when the connection to the server has been lost, though it has already received the information about a scheduled recording.

It would be nice if pyCA would still perform the scheduled recording, even if the server is temporarily unreachable.

**Comment by lkiesow** [comment]
Jan, are you sure that you are using the latest version of pyCA? It should record regardless of the connection. It will log an error that it could not set the state but then continue to execute the recording command.

If you are using the latest version, can you give me your logs for such a failure?

**Comment by JanKoppe** [comment]
Yes, right now we're using 2fd40f83041ae166bcd16dedad29f60f8471cb80 on our Capture Agents. Though I can't find the behaviour I described when searching through the logs, maybe it _did_ record. I'm sorry. I'll keep an eye on this, but I think this issue can be closed again.

**Comment by lkiesow** [comment]
Let me know if you find something after all.
