### ISSUE TITLE
ffmpeg capture command error

### ISSUE THREAD

**Issue by blackyboy** [opencast/pyCA#3]
Hi @lkiesow ,

I have been installed capture agent based upon your documentation and also compiled ffmpeg following the below url.

http://owenashurst.com/?p=242

Every thing is working good (registering capture agent in admin server) When i'm doing schedule for the (PyCA-test) capture agent,the agent can be pick up the recorded schedule from the admin server and we can see the scheduled time in the capture agent terminal and start capturing automatically at the particular time. Unfortunately, we are facing exception (see below) and the capture agent stopped the recording.

Exception:

```
PyCA-test set to idle
No scheduled recording
No scheduled recording
Next scheduled recording: 2014-12-11 10:38:00
Next scheduled recording: 2014-12-11 10:38:00
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libaacplus --enable-librtmp --enable-libmp3lame
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 14.100 / 56. 14.100
  libavformat    56. 15.103 / 56. 15.103
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, lavfi, from 'testsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[swscaler @ 0x2894050] deprecated pixel format used, make sure you did set range correctly
Illegal instruction
Recording failed
16505 set to capture_error
PyCA-test set to idle
```

Is there any thing i need to change? I've to capture the video in H.264 format.

**Comment by lkiesow** [comment]
The ffmpeg output looks a bit odd. Can you give me the full `ffmpeg` command you are using?
On the Raspberry, we are usually using `raspivid`  to capture the raw video stream and `sox` (or ffmpeg, or libav or arecord) to capture the audio separately.

**Comment by blackyboy** [comment]
We are using your same command which in pyca/config.py 

```
CAPTURE_COMMAND = '''ffmpeg -re -f lavfi -r 25 -i testsrc -t %(time)s -map 0:v %(recdir)s/%(recname)s.mp4 -t %(time)s -map 0:v -filter:v select='not(mod(n\,50))' -updatefirst 1 %(previewdir)s/preview.jpg'''
```

As your guide now we using the below command and video started to record.

```
CAPTURE_COMMAND = '''raspivid -n -t %(time)s000 -b 4000000 -fps 30 -o - | \
   ffmpeg -r 30 -i pipe:0 -c:v copy %(recdir)s/%(recname)s.mp4'''
```

Thanks
