### ISSUE TITLE
Retry ingesting a recording

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#30]
If ingesting a recording has failed (e.g. network problems), the user has to ingest the recording by hand outside of pyCA. 

It would be nice if pyCA provides a switch (e.g. `pyCA --ingest-now recording-xyz`) that can be used to retrigger ingesting a recording.

**Comment by lkiesow** [comment]
Should that be a command line option or something on the/a web-ui?

**Comment by JanKoppe** [comment]
A command line option would be a very good start, but being able to
trigger this from the web-ui would be a nice addition. Preferably with a
list of available recordings (dropdown menu).

**Comment by JanKoppe** [comment]
I did a quick implementation in #33 , but I'm not a good python dev at all, so any suggestions for improvements are very, very welcome. It seems to work just fine for me.

**Comment by JanKoppe** [comment]
This has been effectively implemented with the DB integration and process split.

**Comment by lkiesow** [comment]
Not quite (at least not if I did not miss anything). If an upload failed, the status would be set to `FAILED_UPLOADING` and not be picked up again. An easy solution would be to add an action column to the recordings table in the user interface where you have a “Retry Ingest” link which would effectively set the recordings status to `FINISHED_RECORDING` again.

**Comment by JanKoppe** [comment]
My bad, you are right.

**Comment by lkiesow** [comment]
From discussion:

Let's have a re-ingest button in the recording table if state > `RECORDING_FINISHED`

**Comment by JanKoppe** [comment]
Would be handled by #73, PATCH-ing the event state to `Status.FINISHED_RECORDING`, which in turn triggers the ingest service to try another ingest.

**Comment by lkiesow** [comment]
Todo to get this done:

- [ ] Create a `retry_ingest` REST endpoint
- [ ] The endpoint only accepts identifier for recordings which are in the state `FAILED_UPLOADING`
- [ ] The endpoint will change the status to `FINISHED_RECORDING` which will make pyCA automatically try to upload the recording again
- [ ] Add an option to the recording table to trigger an update
