### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#31]
I'm maintaining a Arch User Repository package for pyCA, so that the installation on Arch Linux hosts (which we use at WWU Münster) is standardized. 

Right now the latest official release seems to be severly outdated. A newer official release would be my preferred option, so that I don't have to provide a pyca-git package which would commonly not be suitable for production use.

please tag a new official release.

**Comment by JanKoppe** [comment]
Hi Lars,

is there anything that I could do to help move this along?

Regards

**Comment by lkiesow** [comment]
My original intention was to wait until I get some new thing in but since I'm struggling to get things done: A new minor version is out. Though, with my other projects finished this weekend, I can hopefully, finally find some more time for pyCA starting this week.
