### ISSUE TITLE
Report available disk space in configuration

### ISSUE THREAD

**Issue by smarquard** [opencast/pyCA#36]
The Matterhorn Reference CA and Galicaster report the available disk space in the location where recordings are stored using the configuration property:

capture.cleaner.mindiskspace

(free disk space in bytes).

This is helpful because it allows disk space to be monitored centrally (one of several mechanisms that could be used for doing so).

pyCA should ideally do the same.

**Comment by smarquard** [comment]
Actually it seems the reference CA and Galicaster report different things using this configuration. For the reference CA, this is a minimum value:

```
# The default minimum available disk space, under which recordings are erased from the system
# IN BYTES
# NOTE:  This diskspace value does *NOT* take the reserved disk space for the root user into account
# PLEASE:  Set this value to more than the reserved space on disk (typically 5%) otherwise the minimum disk space
#          checks will not function because there will appear to be enough disk even if you cannot write to the 5%
capture.cleaner.mindiskspace=536870912
```

whereas for Galicaster, it's actual free space.

So maybe there should be a new property to report actual space that is unambiguous.

Corresponding Galicaster issue is:

https://github.com/teltek/Galicaster/issues/437

**Comment by lkiesow** [comment]
This should be specified as part of the new ca api.
It does not really make sense to have different keys for different capture agents.

The question remains if a capture agent should do that at all since there are monitoring tools dedicated to this.

**Comment by smarquard** [comment]
True (the latter part), though speaking as someone whose pyca's recently ran out of disk space, people don't always configure those monitoring tools correctly even when they're available :-) So defense in depth...

Actually I think it's more valuable to set the error state on the CA for low disk space conditions. Reporting the actual free disk space does seem like straying over a separation of concerns boundary.

**Comment by lkiesow** [comment]
Closing this since the disk space is now in the metrics API and the user interface. It's still not defined in the capture agent API.
