### ISSUE TITLE
Update ffmpeg version in Dockerfile

### ISSUE THREAD

**Issue by pitfisher** [opencast/pyCA#368]
Hello! Can you please update the version of ffmpeg used in pyCA's Dockerfile? I'm looking for SRT protocol support. I successfully built local pyCA Docker image with [this](https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz) ffmpeg build and it has SRT support, but it'd be much more convenient to have it in your image. The link to the page with the link to this build is present on an official ffmpeg download page so I guess it's safe to use.

**Comment by lkiesow** [comment]
You are right, that version should work.
Can you file a pull request changing the Dockerfile?

**Comment by pitfisher** [comment]
Thank you for the quick reply!
I filed a [pull request ](https://github.com/opencast/pyCA/pull/369)

**Comment by mtneug** [comment]
Why don't we use the ffmpeg version we build ourselves? If SRT support is missing we should add it.

**Comment by lkiesow** [comment]
That's fine with me as well. For the overall issue, this doesn't matter which version we use.

Right now, the version built for Opencast also target's codecs that Opencast usually needs.
Streaming protocols like SRT and desktop audio and video capture protocols (e.g. pulse) haven't been the focus of that.
But I see no reason why we couldn't add them. Just, I don't have the time to do that right now.
Still, I'm happy to see a pull request for that.

Are you planning to work on that short-term?

**Comment by mtneug** [comment]
Yes, I have a binary linked to libsrt, but have not tested it yet (as in never executed it).

Edit 1: srt is listed in `-protocols`

**Comment by lkiesow** [comment]
Would be nice to add that in the long run.
Short term, I'll just add the other FFmpeg binary.
Once we have updated our build process, we can switch back.
