### ISSUE TITLE
Clarify targeted Python version

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#40]
As you can see in #39, the recent changes are not entirely compatible with Python 3. I will spend a bit of time fixing this, but for the future: Are we targeting only Python 2, as this seems to still be the standard on most distros, or do we support Python 3 as well? Either way, we should clarify it as I couldn't see it while glancing over the README. Thoughts?

**Comment by lkiesow** [comment]
It's true that py2 is still the default on most systems but that is soon about to change (e.g. Fedora will switch to 3 as default in the next version as one of the first big distros). That is why I think we should support both for now.

I would say that we can safely disregard everything < 2.7 as well as 3.0-3.2 (maybe even 3.3?). 

In short, we support what we are testing against (see `.travis.yml`)
