### ISSUE TITLE
installation from packages fails

### ISSUE THREAD

**Issue by khantibalo** [opencast/pyCA#469]
# sudo apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                            
Get:5 https://pyca.deb.opencast.org/opencast-pyca buster InRelease [5,071 B]                                                         
Err:5 https://pyca.deb.opencast.org/opencast-pyca buster InRelease                                                                   
  The following signatures were invalid: EXPKEYSIG 4293B7B1EFDEB3DF PyCA Signing Key (Signing Key for PyCA Debian Repository) <opencast-support@elan-ev.de>
Reading package lists... Done                                                                                                        
W: GPG error: https://pyca.deb.opencast.org/opencast-pyca buster InRelease: The following signatures were invalid: EXPKEYSIG 4293B7B1EFDEB3DF PyCA Signing Key (Signing Key for PyCA Debian Repository) <opencast-support@elan-ev.de>
E: The repository 'https://pyca.deb.opencast.org/opencast-pyca buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by khantibalo** [comment]
sudo apt-key adv --fetch https://pyca.deb.opencast.org/gpg.key
[sudo] password for user: 
Executing: /tmp/apt-key-gpghome.0OTMHls05o/gpg.1.sh --fetch https://pyca.deb.opencast.org/gpg.key
gpg: requesting key from 'https://pyca.deb.opencast.org/gpg.key'
gpg: key 4293B7B1EFDEB3DF: public key "PyCA Signing Key (Signing Key for PyCA Debian Repository) <opencast-support@elan-ev.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1

And then it shows that the key has expired

sudo apt-key finger
pub   rsa4096 2020-05-21 [SC] [expired: 2022-05-21]
      3319 26B3 61F4 704D B10E  4F5A 4293 B7B1 EFDE B3DF
uid           [ expired] PyCA Signing Key (Signing Key for PyCA Debian Repository) <[opencast-support@elan-ev.de](mailto:opencast-support@elan-ev.de)>

**Comment by lkiesow** [comment]
Just tested with Debian 12 and it works as expected.
But the key has been replaced since. So that was the problem.
Closing this as it has been resolved.
