### ISSUE TITLE
capture network stream

### ISSUE THREAD

**Issue by kermorgant** [opencast/pyCA#5]
Hi,
The readme states pyca could capture network stream.
How would one do that ?

Would be great if the config.py had an example as there are already several there.

Regards
Mikael Kermorgant

**Comment by lkiesow** [comment]
The problem with that is that there are various possible ways to get a network stream and different kinds of network streams. But let me give you an example using ffmpeg.

First let's generate a network stream. This would usually come from your device, but for the sake of easy testing, lets run:

```
ffmpeg -re -f lavfi -i testsrc -c:v mpeg4 -b:v 800k -g 4 -f mpegts -bf 0 udp://127.0.0.1:8888
```

This will generate a test video, encode it as mpeg4 and send it as network stream to a local udp socket, port 8888. Now here is a way to capture such a network stream:

```
ffmpeg -i 'udp://0.0.0.0:8888' -t 60 -c copy out.mkv
```

This would now tell FFmpeg to listen to UDP port 8888 for 60 seconds and write the video to a file called `out.mkv`. Besides from capturing raw streams over TCP or UPD, FFmpeg can handle a lot of different streaming protocols like RTP, RTMP, HLS, … Just have a look at the documentation.

Of course, you could also use other capture software like GStreamer or libav if you prefer that over FFmpeg.
