### ISSUE TITLE
Set Capture Agent to Offline

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#53]
The capture agent state offline is introduced with Opencast 2.4:

https://bitbucket.org/opencast-community/matterhorn/pull-requests/1127/mh-11708-cas-are-never-shown-as-offline/diff

**Comment by JanKoppe** [comment]
I've been looking at this. ~~Two~~ thoughts:

__How do we define that a capture agent is offline?__

My proposal is that if the scheduler process is not running, the capture agent is marked as _offline_. Without the scheduler process, the capture agent is not able to receive new events, therefore is for all intents and purposes offline from opencasts point of view. 

If the actual connection to opencast, used for scheduler and ingest, is broken and thus the capture agent is in the classical sense 'offline', we are not able to update this status anyway.

Edit:
This got too big, see #64
