### ISSUE TITLE
terminate capture processes after timeout

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#57]
- Optionally send `sigterm` at end of recording time + configurable time
- Send `sigkill` at end of recording time + configurable time

**Comment by JanKoppe** [comment]
This should be entirely optional. What if the users want to do some processing after the recording, which still takes time?

**Comment by lkiesow** [comment]
I guess, another option does not hurt, though, it's then in a way conflicting with other recordings and doing the post-processing in Opencast would make more sense.

**Comment by lkiesow** [comment]
This feature is basically done.
Needs a final review before I create the pull request:

https://github.com/lkiesow/pyCA/tree/term-time
