### ISSUE TITLE
keep-alive for internal services

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#76]
The current agent state implementation (#64) cannot clearly detect stuck or crashed services. We should implement a keep-alive function to fix this. I'm working on this right now. My approach is to add a timestamp column to the service state table that will be updated on `set_service_status()` call, including the main loops for the services. This timestamp can then be used to check if a service is still alive (i.e. not older than xx seconds).

**Comment by JanKoppe** [comment]
This would be made somewhat obsolete by #144. One upside of a internal, python-only solution would be that it would work on a non systemd distribution, but I think we can neglect this because afaik pretty much every relevant system for pyca nowadays uses systemd.

**Comment by lkiesow** [comment]
Closing this since it's now taken care of by systemd.
