### ISSUE TITLE
System Logger not usable

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#82]
Currently pyCA is only able to log to `STDERR`. Although this is not that important if running with a systemd service file or probably even preferred in a docker container, there are some situations where you would rather use `/dev/log` for logging:

 * Distributions without Systemd (a lot embedded linux, some Gentoo (I think it is the default), Alpine Linux, ...)
 * Syslog forwarding to a remote host to gather all information in one spot or maybe for security reasons

Also you are able to use the great power of log levels and facilities. IMHO the best way would be to make this configurable.

**Comment by JanKoppe** [comment]
Could we implement this in the `start.sh`, so that distribution packages can handle this independently?

**Comment by lkiesow** [comment]
This is basically missing configuration for the Python logging module we use. The more general issue here is to expose the Python logging configuration to:

- Use a logging [file handler](https://docs.python.org/2/library/logging.handlers.html#filehandler)
- Use a [syslog handler](https://docs.python.org/2/library/logging.handlers.html#sysloghandler)
- Add log level adjustment

**Comment by shaardie** [comment]
Something like https://gist.github.com/shaardie/3e45b985fc52481184e7179f007e2051

**Comment by lkiesow** [comment]
Kind of like that. Just configurable.
If you want, add a logging section to the config file
