### ISSUE TITLE
global configuration before local configuration

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#84]
Probably this is a wanted behavior, but I think it is not canonical to ignore the local `./etc/config` if a global `/etc/config` exists.

The canonical way would be that global and local overrides default and local overrides global.

**Comment by lkiesow** [comment]
I do have no strong feelings about this. Go ahead and switch the default, if you like. @JanKoppe ?

**Comment by JanKoppe** [comment]
No strong feelings either. Used to using something like a `-c configfile` flag, but this could work, too. Maybe add a logging-message if a local config file is overriding global config, and make a note on this in the readme (usual approach of just copying the config file to `/etc` won't work as expected anymore.)

**Comment by shaardie** [comment]
There is a `simplistic and minimalistic in code and functionality` in your goals for pyCA. Thererfore you could think of even drop the one of the configuration pathes (`/etc/`, ... or `./etc`).

**Comment by shaardie** [comment]
Problem with logging is that it is not configured at that point ;) Maybe simply print to stdout or stderr.

**Comment by lkiesow** [comment]
The configuration file is used to load the configuration. That routine could, if it does not fail, log which config file it used.
