### ISSUE TITLE
Do not catch all exception silently

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#88]
I know this issue is a little bit universal, but I found multiple places in the code were simply all exceptions are catched. This is a not very pythonic way to write code and make debugging very difficult.

I found this a bit entertaining blog entry about it https://realpython.com/blog/python/the-most-diabolical-python-antipattern/

Something like that should never happen:

    try:
        BANANA
    except:
        pass
    print("Everything is fine")

**Comment by lkiesow** [comment]
With the latest updates, this task should be more or less done.
