### ISSUE TITLE
Running pyCA with UI using "&" will cause strange behaviour

### ISSUE THREAD

**Issue by gregapodobnik** [opencast/pyCA#99]
When running pyCA with UI using command
> ./start.sh&; ./start.sh ui

it will not create any recordings. 

The recording commands will be triggered but then the pyCA process will be suspended

> [3]  + 28097 suspended (tty output)  ./start.sh

... and recordings will not be created and all further processes for that event will be canceled. 

Also the UI will list the Recording processes as "recording" indefinitely. But strangely the top semaphone will show all Processed and Capture as idle.

**Comment by lkiesow** [comment]
Short summary:

FFmpeg is causing the problem. This will not run either:

    ffmpeg … out.mp4 &

It can be solved by providing FFmpeg with a pipe for stdin it can read from:

    ffmpeg … out.mp4 < /dev/null &

pyCA could generally create pipes for stdin, stdout and stderr. They can even be used for logging and potentially for controlling the sub-process.

**Comment by JanKoppe** [comment]
I would say it's the users responsibility to make their recording_command work, but, yes, our default command should work in this way.

Logging for the recording_command can easily be done by the user as well (e.g. `>> {{dir}}/{{recording}}-log.txt`) which is the most convenient way to get insight after a crash, IMHO. I don't see the necessity to provide pipes. 

Controlling sub-processes OTH would be very interesting, especially for sending pause signals or stop signals for ad-hoc recordings.

**Comment by lkiesow** [comment]
> I would say it's the users responsibility to make their recording_command work, but, yes, our default command should work in this way.

True and I will fix that in a moment. 
But being more robust is probably not a bad thing :-P

> Logging for the recording_command can easily be done by the user as well (e.g. >> {{dir}}/{{recording}}-log.txt) which is the most convenient way to get insight after a crash, IMHO. I don't see the necessity to provide pipes.

Sorry, but that will not work. The capture command is launched as sub-process (`Popen` call) and not inside a shell. Hence a user cannot specify any pipes. You would also loose system logging capabilities for this. 

> Controlling sub-processes OTH would be very interesting, especially for sending pause signals or stop signals for ad-hoc recordings.

The basics for that are almost done. See the [term-time](https://github.com/lkiesow/pyCA/tree/term-time) branch in my repository. Although, for ad-hoc command, we would need more communication with the db.

**Comment by JanKoppe** [comment]
> > Logging for the recording_command can easily be done by the user as well (e.g. >> {{dir}}/{{recording}}-log.txt) which is the most convenient way to get insight after a crash, IMHO. I don't see the necessity to provide pipes.

> Sorry, but that will not work. The capture command is launched as sub-process (Popen call) and not inside a shell. Hence a user cannot specify any pipes. You would also loose system logging capabilities for this.

Ah, yes, not if you put it in the recording_command line. I'm cheating a bit and just call a shell script that does the actual recording, because squeezing my solution into one line would be very ugly. That makes sense.

**Comment by lkiesow** [comment]
Ok, a shell script would actually work

**Comment by lkiesow** [comment]
#100 should fix the problem.
Interestingly the `-nostdin` FFmpeg option does not fix the problem.

I still think adding proper logging would be a nice touch but that in an enhancement for later.

**Comment by lkiesow** [comment]
Updated the pull request to attach /dev/null instead of opening a pipe.
Should be more robust.
